1. Импорт библиотеки NumPy с общепринятым сокращением.

In [2]:
import numpy as np

2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.

In [8]:
# 2.1 Создание массива из обычного списка
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [9]:
# 2.2 Создание двумерного массива из списка списков
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# 2.3 Создание массива нулей с помощью zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
# 2.4 Создание двумерного массива единиц с помощью ones
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# 2.5 Создание массива с последовательностью чисел с помощью arange
np.arange(0, 10, 2)  # от 0 до 10 с шагом 2

array([0, 2, 4, 6, 8])

3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [26]:
# 3. Демонстрация атрибутов shape и dtype
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape 

(2, 3)

In [25]:
# 3.1 Показ типа данных массива
arr.dtype 

dtype('int64')

4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.

In [27]:
# 4.1 Индексирование - получение отдельного элемента
arr = np.array([10, 20, 30, 40, 50])
arr[2]  # получение третьего элемента 

np.int64(30)

In [28]:
# 4.2 Срезы, извлечение подмассива
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:7]  # элементы с индексом 2 до 6 (7 не включается)

array([2, 3, 4, 5, 6])

5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

In [35]:
# 5.1 Векторные операции, поэлементное сложение
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b  # поэлементное сложение

array([ 6,  8, 10, 12])

In [34]:
# 5.2 поэлементное умножение
a * b  # поэлементное умножение (не матричное)

array([ 5, 12, 21, 32])

In [30]:
# 5.3 вычисление среднего значения
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.mean(arr)  # среднее арифметическое

np.float64(5.5)

In [32]:
# 5.4 сумма элементов
np.sum(arr)  # сумма всех элементов

np.int64(10)

In [33]:
# 5.5 максимальное и минимальное значение
arr = np.array([3, 1, 7, 2, 9, 4])
np.max(arr), np.min(arr)  # максимальный и минимальный элементы

(np.int64(9), np.int64(1))

In [31]:
# 5.6 Демонстрация поэлементных операций с разными формами (broadcasting)
arr = np.array([1, 2, 3, 4])
arr + 10  # прибавление числа к каждому элементу

array([11, 12, 13, 14])